change to push to GHCR

diff --git a/.github/workflows/build-and-push-image.yml b/.github/workflows/build-and-push-image.yml
--- a/.github/workflows/build-and-push-image.yml
+++ b/.github/workflows/build-and-push-image.yml
@@ -21,7 +21,7 @@ permissions:
 
 env:
   HELM_EXPERIMENTAL_OCI: 1
-  REGISTRY: docker.io  # For Docker Hub registry
+  REGISTRY: ghcr.io  # GitHub Container Registry
 
 jobs:
   build-and-push:
@@ -36,11 +36,12 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Login to Docker Hub
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build and Push geoipupdate Multi-Arch Images
         run: |
@@ -48,8 +49,8 @@ jobs:
           if [ -z "${{inputs.image_tag}}" ]; then 
             BUILD_SCOPE='latest'
           fi
-          echo "Building with BUILD_SCOPE=$BUILD_SCOPE"
-          make image-build-and-push-multi-arch BUILD_SCOPE="$BUILD_SCOPE"
+          echo "Building with ghcr.io/vungle/geoipupdate:$BUILD_SCOPE"
+          make image-build-and-push-multi-arch PROJECT_IMAGE_MULTIARCH="ghcr.io/vungle/geoipupdate:$BUILD_SCOPE"
 
       - name: Verify Image Push
         run: |
@@ -57,5 +58,5 @@ jobs:
           if [ -z "${{inputs.image_tag}}" ]; then 
             BUILD_SCOPE='latest'
           fi
-          echo "Verifying image: vungle/geoipupdate:$BUILD_SCOPE"
-          docker manifest inspect vungle/geoipupdate:$BUILD_SCOPE || echo "Image verification failed"
+          echo "Verifying image: ghcr.io/vungle/geoipupdate:$BUILD_SCOPE"
+          docker manifest inspect ghcr.io/vungle/geoipupdate:$BUILD_SCOPE || echo "Image verification failed"
